# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_myuser_profile_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUser',
            new_name='Profile',
        ),
    ]
